name: Daily Currency Bot

on:
  schedule:
    # Время указано по UTC (Всемирное время). 
    # Например, 03:30 утра по UTC соответствует 08:30 утра в Душанбе (+5).
    - cron: '30 3 * * *' 
  workflow_dispatch: # Позволяет запускать вручную кнопку в любой момент для теста

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python bot.py
